### PR TITLE
[Bugfix] Added Effects to other levels

### PR DESCRIPTION
**Pull request by Snow106**
Changed effect to take in a deltaTime
time in advanced shader is no longer exponential (it adds only once)
Added lerp-ish thing to effect so it slows down and matches the static tiles
This caused the effect to change slightly 🤷

### CODE REVIEW

**Review by KevinAlexV — DISMISSED** [review]
Lookin good

**Review by KevinAlexV — DISMISSED** [review]

**Review by Hevano — DISMISSED** [review]
Looks good, just in time too

**Review by KevinAlexV — APPROVED** [review]
I like it

**Review by Aiden-Lonquist — APPROVED** [review]
Great work :)

**Pull request merged**
